# Generated by Django 2.0.5 on 2018-07-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=20)),
                ('total_seats', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusAndCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testbusapp.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_i', models.IntegerField()),
                ('seat_j', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testbusapp.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_i', models.IntegerField()),
                ('seat_j', models.IntegerField()),
                ('seat_booked_date', models.DateField(blank=True, null=True)),
                ('source_city', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testbusapp.Bus')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testbusapp.Seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatBookingDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_booked_date', models.DateField()),
                ('passenger_name', models.CharField(default=None, max_length=100)),
                ('passenger_age', models.IntegerField(default=20)),
                ('passenger_gender', models.CharField(default=None, max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testbusapp.Bus')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testbusapp.Seat')),
            ],
        ),
        migrations.CreateModel(
            name='TicketIdAndSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.CharField(max_length=1000)),
                ('seats_booked_date', models.DateField(blank=True, null=True)),
                ('source_city', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testbusapp.Bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default=None, max_length=10)),
                ('mobile', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='busandcity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='testbusapp.City'),
        ),
        migrations.AddField(
            model_name='busandcity',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city', to='testbusapp.City'),
        ),
        migrations.AddField(
            model_name='bus',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city_s', to='testbusapp.City'),
        ),
        migrations.AddField(
            model_name='bus',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city_s', to='testbusapp.City'),
        ),
    ]
